# Generated by Django 4.2.6 on 2024-02-25 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=45, null=True)),
                ('description', models.CharField(max_length=450, null=True)),
                ('location', models.CharField(max_length=45, null=True)),
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educon.college')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('college_id', 'course_id'), name='unique_college_course'),
        ),
    ]
